default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: learning-exchange_development

test:
  <<: *default
  database: learning-exchange_test

production:
  <<: *default
  database: learning-exchange_production
  username: learning-exchange
  password: <%= ENV['LEARNING-EXCHANGE_DATABASE_PASSWORD'] %>
